name: Build and create release

on:
  push:
    tags:
      - '**'

jobs:
  build-upload:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      run: sh scripts/pullFromAur.sh

    - name: Create ISO
      run: sh scripts/build.sh

    - name: Add ISO to release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        artifacts: /lukeMechArch/*.iso
