name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    container:
      image: docker://archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  
    - name: Get code from repo
      uses: actions/checkout@main

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Install packages
      run: pacman -Syyu archiso --noconfirm

    - name: Build ISO
      run: sh build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch ${{ steps.date.outputs.date }}
        path: /build