name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    container:
      image: docker://archlinux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Install needed packages
      run: pacman --Syyu archiso --noconfirm

    - name: Build ISO
      run: ./build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch
        path: build/