name: Build and create release

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      id: info
      run: |
        sh scripts/pullFromAur.sh
        echo "ver=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT   

    - name: Create ISO
      run: sh scripts/build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        path: /lukeMechArch/*.iso
        

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - name: Clone code
      uses: actions/checkout@main

    - name: Read release.md
      id: info
      run: |
        r=$(cat release.md)        
        r="${r//'%'/'%25'}"                          
        r="${r//$'\n'/'%0A'}"                   
        r="${r//$'\r'/'%0D'}"                         
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT  
        echo "ver=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT   

    - name: Retore ISO from artifacts
      uses: actions/download-artifact@main
      with:
        path: /iso

    - name: Create release
      uses: svenstaro/upload-release-action@master
      with:
        file_glob: true
        overwrite: true
        file: /iso/**/*.iso
        release_name: ${{ steps.info.outputs.ver }}
        body: ${{ steps.read_release.info.RELEASE_BODY }}
