name: Build and create release

on:
  push:
    tags:
      - '**'

jobs:
  build-upload:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Read release.md to use as a body of new release
      id: read_release
      shell: bash
      run: |
        r=$(cat path/to/release.md)        
        r="${r//'%'/'%25'}"                          
        r="${r//$'\n'/'%0A'}"                   
        r="${r//$'\r'/'%0D'}"                         
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT         

    - name: Build AUR packages
      run: sh scripts/pullFromAur.sh

    - name: Create ISO
      run: sh scripts/build.sh

    - name: Create release
      uses: svenstaro/upload-release-action@master
      with:
        file_glob: true
        file: /lukeMechArch/*.iso
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
