name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Get some info
      id: info
      run: |
        echo "num=$(date +'%y.%m-')" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse --short "$GITHUB_SHA)" >> $GITHUB_OUTPUT
    
    - name: Install packages
      run: pacman -Syyu archiso --noconfirm

    - name: Build ISO
      run: sh build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch ${{ steps.info.outputs.num }}${{ steps.info.outputs.sha }}
        path: /build