name: Build ISO

on:
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      id: info
      run: |
        sh scripts/pullFromAur.sh
        echo "num=$(date +'%y.%m')" >> $GITHUB_OUTPUT 
        echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Create ISO
      run: |
        sh scripts/build.sh

    - name: Mount cache
      uses: actions/cache@main
      with:
        path: /iso
        key: Builded ISO

    - name: Add ISO to cache
      run: |
        rm -rf /iso/*
        cp /lukeMechArch/* /iso

  upload:

    runs-on: ubuntu-latest
    
    steps:  

    - name: Mount cache
      uses: actions/cache@main
      with:
        path: /iso
        key: Builded ISO

    - name: Get ISO name
      id: info
      run: |
        cd /iso
        echo "name=$(ls)" >> $GITHUB_OUTPUT 

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: ${{ steps.info.outputs.name }}
        path: /iso