name: Build and create release

on:
  push:
    tags:
      - '**'

jobs:
  build-upload:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      run: sh scripts/pullFromAur.sh

    - name: Create ISO
      run: sh scripts/build.sh

    - name: Add ISO to release
      uses: svenstaro/upload-release-action@master
      with:
        append_body: true
        file_glob: true
        file: /lukeMechArch/*.iso
