name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Get some info
      id: info
      run: |
        echo "num=$(date +'%y.%m-')" >> $GITHUB_OUTPUT
        echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Download AUR packages
      run: sh downloadAur.sh

    - name: Build ISO
      run: sh build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch ${{ steps.info.outputs.num }}${{ steps.info.outputs.sha }}
        path: /build
