name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      run: sh scripts/pullFromAur.sh

    - name: Create ISO
      run: sh scripts/build.sh

    - name: Get date & commit number
      id: info
      run: echo "num=$(date +'%y.%m')" >> $GITHUB_OUTPUT && echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Rename ISO
      run: mv /lukeMechArch/*.iso "/lukeMechArch/LukeMechArch ${{ steps.info.outputs.num }} (${{ steps.info.outputs.sha }}).iso"

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch ${{ steps.info.outputs.num }} (${{ steps.info.outputs.sha }})
        path: /lukeMechArch
