name: Check building

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  check:

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      id: info
      run: |
        sh scripts/pullFromAur.sh

    - name: Check if all ISO packages are available
      run: |
        rm -rf /etc/pacman.conf
        mv archFiles/pacman.conf /etc/
        pacman -Syu - < archFiles/bootstrap_packages.x86_64
        pacman -Syu - < archFiles/packages.x86_64