name: DEV Check & build

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  build-aur:

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      run: |
        sh scripts/pullFromAur.sh
      
    - name: Add AUR repository to cache
      uses: actions/cache@main
      with:
        path: /repo
        key: aur-packages


  check-packages:
    needs: build-aur

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Mount AUR repository
      uses: actions/cache@main
      with:
        path: /repo
        key: aur-packages

    - name: Check if all ISO packages are available
      run: |
        rm -rf /etc/pacman.conf
        cp archFiles/pacman.conf /etc/
        pacman -Syu - < archFiles/bootstrap_packages.x86_64 --noconfirm
        pacman -Syu - < archFiles/packages.x86_64 --noconfirm

  create-iso:
    needs: build-aur

    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined

    steps:

    - name: Clone code
      uses: actions/checkout@main

    - name: Mount AUR repository
      uses: actions/cache@main
      with:
        path: /repo
        key: aur-packages

    - name: Create ISO
      run: |
        sh scripts/build.sh
        mv /lukeMechArch/*.iso "/lukeMechArch/LukeMechArch-${{ steps.info.outputs.num }}-DEV-${{ steps.info.outputs.sha }}.iso"        

    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        name: LukeMechArch ${{ steps.info.outputs.num }} DEV - ${{ steps.info.outputs.sha }}
        path: /lukeMechArch