name: DEV Check & build

on:
  push:
    branches-ignore:    
      - "main"

jobs:
  build-upload:

    runs-on: ubuntu-latest
    permissions: read-all, write-all
    container:
      image: archlinux
      options: --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    
    steps:  

    - name: Clone code
      uses: actions/checkout@main

    - name: Build AUR packages
      id: info
      run: |
        sh scripts/pullFromAur.sh
        echo "num=$(date +'%y.%m')" >> $GITHUB_OUTPUT 
        echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Create ISO
      run: |
        sh scripts/build.sh
        mv /lukeMechArch/*.iso "/lukeMechArch/LukeMechArch-${{ steps.info.outputs.num }}-DEV-${{ steps.info.outputs.sha }}.iso"  
        
    - name: Upload ISO
      uses: actions/upload-artifact@main
      with:
        path: /lukeMechArch
        name: LukeMechArch ${{ steps.info.outputs.num }} DEV-${{ steps.info.outputs.sha }}
